# =====================================================
# DOCKER COMPOSE MELHORADO - ATENDEAI 2.0
# Correções de conectividade e volume mounts
# =====================================================

version: '3.8'

services:
  # =====================================================
  # REDIS CACHE CLUSTER (OTIMIZADO)
  # =====================================================
  redis:
    image: redis:7-alpine
    container_name: atendeai-redis
    restart: unless-stopped
    command: redis-server --appendonly yes --requirepass redis123 --maxmemory 512mb --maxmemory-policy allkeys-lru
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - atendeai-network
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "-a", "redis123", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    environment:
      - REDIS_PASSWORD=redis123

  # =====================================================
  # AUTH SERVICE (CORRIGIDO)
  # =====================================================
  auth-service:
    build:
      context: ./backend/services/auth-service
      dockerfile: Dockerfile
    container_name: atendeai-auth-service
    restart: unless-stopped
    environment:
      NODE_ENV: development
      PORT: 3001
      DATABASE_URL: postgresql://postgres:Supa201294base@db.kytphnasmdvebmdvvwtx.supabase.co:5432/postgres
      REDIS_URL: redis://:redis123@redis:6379
      JWT_SECRET: your-super-secret-jwt-key-change-in-production
      JWT_ACCESS_TOKEN_EXPIRY: 15m
      JWT_REFRESH_TOKEN_EXPIRY: 7d
      BCRYPT_ROUNDS: 12
      SUPABASE_URL: https://kytphnasmdvebmdvvwtx.supabase.co
      SUPABASE_ANON_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt5dHBobmFzbWR2ZWJtZHZ2d3R4Iiwicm9sIjoiYW5vbiIsImlhdCI6MTc1NTYyMjgxMCwiZXhwIjoyMDcxMTk4ODEwfQ.gfH3VNqxLZWAbjlrlk44VrBdyF1QKv7CyOSLmhFwbqA
      SUPABASE_SERVICE_ROLE_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt5dHBobmFzbWR2ZWJtZHZ2d3R4Iiwicm9sIjoic2VydmljZV9yb2xlIiwiaWF0IjoxNzU1NjIyODEwLCJleHAiOjIwNzExOTg4MTB9LjM2SXA5Tld2cWg2YWVGUXVvd1Y3OXI1NEMyWVFQYzVOLU1uX2RuMlFENzA
      # Configurações de conectividade
      DATABASE_CONNECTION_TIMEOUT: 30000
      DATABASE_POOL_SIZE: 10
      DATABASE_IDLE_TIMEOUT: 30000
      REDIS_CONNECTION_TIMEOUT: 10000
      REDIS_RETRY_ATTEMPTS: 3
    ports:
      - "3001:3001"
    volumes:
      # CORREÇÃO: Volume mount otimizado para desenvolvimento
      - ./backend/services/auth-service:/app:delegated
      - /app/node_modules
      - /app/.git
    networks:
      - atendeai-network
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    # CORREÇÃO: Configurações de rede otimizadas
    extra_hosts:
      - "host.docker.internal:host-gateway"
    dns:
      - 8.8.8.8
      - 8.8.4.4

  # =====================================================
  # CLINIC SERVICE (CORRIGIDO)
  # =====================================================
  clinic-service:
    build:
      context: ./backend/services/clinic-service
      dockerfile: Dockerfile
    container_name: atendeai-clinic-service
    restart: unless-stopped
    environment:
      NODE_ENV: development
      PORT: 3003
      DATABASE_URL: postgresql://postgres:Supa201294base@db.kytphnasmdvebmdvvwtx.supabase.co:5432/postgres
      REDIS_URL: redis://:redis123@redis:6379
      JWT_SECRET: your-super-secret-jwt-key-change-in-production
      SUPABASE_URL: https://kytphnasmdvebmdvvwtx.supabase.co
      SUPABASE_ANON_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt5dHBobmFzbWR2ZWJtZHZ2d3R4Iiwicm9sIjoiYW5vbiIsImlhdCI6MTc1NTYyMjgxMCwiZXhwIjoyMDcxMTk4ODEwfQ.gfH3VNqxLZWAbjlrlk44VrBdyF1QKv7CyOSLmhFwbqA
      SUPABASE_SERVICE_ROLE_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt5dHBobmFzbWR2ZWJtZHZ2d3R4Iiwicm9sIjoic2VydmljZV9yb2xlIiwiaWF0IjoxNzU1NjIyODEwLCJleHAiOjIwNzExOTg4MTB9LjM2SXA5Tld2cWg2YWVGUXVvd1Y3OXI1NEMyWVFQYzVOLU1uX2RuMlFENzA
      # Configurações de conectividade
      DATABASE_CONNECTION_TIMEOUT: 30000
      DATABASE_POOL_SIZE: 10
      DATABASE_IDLE_TIMEOUT: 30000
    ports:
      - "3003:3003"
    volumes:
      - ./backend/services/clinic-service:/app:delegated
      - /app/node_modules
      - /app/.git
    networks:
      - atendeai-network
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3003/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    extra_hosts:
      - "host.docker.internal:host-gateway"
    dns:
      - 8.8.8.8
      - 8.8.4.4

  # =====================================================
  # WHATSAPP SERVICE (CORRIGIDO)
  # =====================================================
  whatsapp-service:
    build:
      context: ./backend/services/whatsapp-service
      dockerfile: Dockerfile
    container_name: atendeai-whatsapp-service
    restart: unless-stopped
    environment:
      NODE_ENV: development
      PORT: 3007
      DATABASE_URL: postgresql://postgres:Supa201294base@db.kytphnasmdvebmdvvwtx.supabase.co:5432/postgres
      REDIS_URL: redis://:redis123@redis:6379
      JWT_SECRET: your-super-secret-jwt-key-change-in-production
      SUPABASE_URL: https://kytphnasmdvebmdvvwtx.supabase.co
      SUPABASE_ANON_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt5dHBobmFzbWR2ZWJtZHZ2d3R4Iiwicm9sIjoiYW5vbiIsImlhdCI6MTc1NTYyMjgxMCwiZXhwIjoyMDcxMTk4ODEwfQ.gfH3VNqxLZWAbjlrlk44VrBdyF1QKv7CyOSLmhFwbqA
      SUPABASE_SERVICE_ROLE_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt5dHBobmFzbWR2ZWJtZHZ2d3R4Iiwicm9sIjoic2VydmljZV9yb2xlIiwiaWF0IjoxNzU1NjIyODEwLCJleHAiOjIwNzExOTg4MTB9LjM2SXA5Tld2cWg2YWVGUXVvd1Y3OXI1NEMyWVFQYzVOLU1uX2RuMlFENzA
      # WhatsApp Business API Configuration
      WHATSAPP_BUSINESS_ACCOUNT_ID: 698766983327246
      WHATSAPP_PHONE_NUMBER_ID: 698766983327246
      WHATSAPP_ACCESS_TOKEN: EAASAuWYr9JgBPIK7v7aqrbiprhBWXJHZBt24BQbjDZAclTltVEXhHBM2lhOmwAsTcA2p0ZCEqLySZBkA4dhiGLv1EBtlFwA3ApL6FY8aIWzxChnGxrqaeJmIkHytXgkvr9veEU9jUcHKNGt6kzbZALHV3XZBOeOGhJGpeZBLZB0DOi7qI41YzdOGlkSOBZASrZBgZDZD
      WHATSAPP_WEBHOOK_VERIFY_TOKEN: atendeai_webhook_verify_2024
      WHATSAPP_API_VERSION: v18.0
      WHATSAPP_BASE_URL: https://graph.facebook.com
      WHATSAPP_WEBHOOK_PATH: /webhook/whatsapp
      WHATSAPP_MAX_RETRIES: 3
      WHATSAPP_RETRY_DELAY: 1000
      WEBHOOK_SIGNATURE_SECRET: atendeai_webhook_signature_secret_2024
      # Service URLs
      CLINIC_SERVICE_URL: http://clinic-service:3003
      CONVERSATION_SERVICE_URL: http://conversation-service:3005
      APPOINTMENT_SERVICE_URL: http://appointment-service:3006
      # Configurações de conectividade
      DATABASE_CONNECTION_TIMEOUT: 30000
      DATABASE_POOL_SIZE: 10
      DATABASE_IDLE_TIMEOUT: 30000
    ports:
      - "3007:3007"
    volumes:
      - ./backend/services/whatsapp-service:/app:delegated
      - /app/node_modules
      - /app/.git
    networks:
      - atendeai-network
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3007/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    extra_hosts:
      - "host.docker.internal:host-gateway"
    dns:
      - 8.8.8.8
      - 8.8.4.4

  # =====================================================
  # GOOGLE CALENDAR SERVICE (CORRIGIDO)
  # =====================================================
  google-calendar-service:
    build:
      context: ./backend/services/google-calendar-service
      dockerfile: Dockerfile
    container_name: atendeai-google-calendar-service
    restart: unless-stopped
    environment:
      NODE_ENV: development
      PORT: 3008
      DATABASE_URL: postgresql://postgres:Supa201294base@db.kytphnasmdvebmdvvwtx.supabase.co:5432/postgres
      REDIS_URL: redis://:redis123@redis:6379
      JWT_SECRET: your-super-secret-jwt-key-change-in-production
      SUPABASE_URL: https://kytphnasmdvebmdvvwtx.supabase.co
      SUPABASE_ANON_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt5dHBobmFzbWR2ZWJtZHZ2d3R4Iiwicm9sIjoiYW5vbiIsImlhdCI6MTc1NTYyMjgxMCwiZXhwIjoyMDcxMTk4ODEwfQ.gfH3VNqxLZWAbjlrlk44VrBdyF1QKv7CyOSLmhFwbqA
      SUPABASE_SERVICE_ROLE_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt5dHBobmFzbWR2ZWJtZHZ2d3R4Iiwicm9sIjoic2VydmljZV9yb2xlIiwiaWF0IjoxNzU1NjIyODEwLCJleHAiOjIwNzExOTg4MTB9LjM2SXA5Tld2cWg2YWVGUXVvd1Y3OXI1NEMyWVFQYzVOLU1uX2RuMlFENzA
      # Google Calendar API Configuration
      GOOGLE_CLIENT_ID: 367439444210-phr1e6oiu8hnh5vm57lpoud5lhrdda2o.apps.googleusercontent.com
      GOOGLE_CLIENT_SECRET: GOCSPX-your_client_secret_here
      GOOGLE_REDIRECT_URI: http://localhost:3008/auth/google/callback
      GOOGLE_API_KEY: your_google_api_key_here
      GOOGLE_CALENDAR_ID: primary
      GOOGLE_TIMEZONE: America/Sao_Paulo
      # Calendar Settings
      DEFAULT_APPOINTMENT_DURATION: 30
      BUFFER_TIME: 15
      WORKING_HOURS_START: 08:00
      WORKING_HOURS_END: 18:00
      WORKING_DAYS: monday,tuesday,wednesday,thursday,friday
      MAX_ADVANCE_BOOKING: 90
      MIN_ADVANCE_BOOKING: 1
      # Synchronization Settings
      BIDIRECTIONAL_SYNC: true
      AUTO_SYNC: true
      SYNC_ON_CREATE: true
      SYNC_ON_UPDATE: true
      SYNC_ON_DELETE: true
      CONFLICT_RESOLUTION: local
      # Service URLs
      CLINIC_SERVICE_URL: http://clinic-service:3003
      APPOINTMENT_SERVICE_URL: http://appointment-service:3006
      # Configurações de conectividade
      DATABASE_CONNECTION_TIMEOUT: 30000
      DATABASE_POOL_SIZE: 10
      DATABASE_IDLE_TIMEOUT: 30000
    ports:
      - "3008:3008"
    volumes:
      - ./backend/services/google-calendar-service:/app:delegated
      - /app/node_modules
      - /app/.git
    networks:
      - atendeai-network
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3008/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    extra_hosts:
      - "host.docker.internal:host-gateway"
    dns:
      - 8.8.8.8
      - 8.8.4.4

  # =====================================================
  # CONVERSATION SERVICE (CORRIGIDO)
  # =====================================================
  conversation-service:
    build:
      context: ./backend/services/conversation-service
      dockerfile: Dockerfile
    container_name: atendeai-conversation-service
    restart: unless-stopped
    environment:
      NODE_ENV: development
      PORT: 3005
      DATABASE_URL: postgresql://postgres:Supa201294base@db.kytphnasmdvebmdvvwtx.supabase.co:5432/postgres
      REDIS_URL: redis://:redis123@redis:6379
      JWT_SECRET: your-super-secret-jwt-key-change-in-production
      SUPABASE_URL: https://kytphnasmdvebmdvvwtx.supabase.co
      SUPABASE_ANON_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt5dHBobmFzbWR2ZWJtZHZ2d3R4Iiwicm9sIjoiYW5vbiIsImlhdCI6MTc1NTYyMjgxMCwiZXhwIjoyMDcxMTk4ODEwfQ.gfH3VNqxLZWAbjlrlk44VrBdyF1QKv7CyOSLmhFwbqA
      SUPABASE_SERVICE_ROLE_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt5dHBobmFzbWR2ZWJtZHZ2d3R4Iiwicm9sIjoic2VydmljZV9yb2xlIiwiaWF0IjoxNzU1NjIyODEwLCJleHAiOjIwNzExOTg4MTB9LjM2SXA5Tld2cWg2YWVGUXVvd1Y3OXI1NEMyWVFQYzVOLU1uX2RuMlFENzA
      # Configurações de conectividade
      DATABASE_CONNECTION_TIMEOUT: 30000
      DATABASE_POOL_SIZE: 10
      DATABASE_IDLE_TIMEOUT: 30000
    ports:
      - "3005:3005"
    volumes:
      - ./backend/services/conversation-service:/app:delegated
      - /app/node_modules
      - /app/.git
    networks:
      - atendeai-network
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3005/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    extra_hosts:
      - "host.docker.internal:host-gateway"
    dns:
      - 8.8.8.8
      - 8.8.4.4

  # =====================================================
  # APPOINTMENT SERVICE (CORRIGIDO)
  # =====================================================
  appointment-service:
    build:
      context: ./backend/services/appointment-service
      dockerfile: Dockerfile
    container_name: atendeai-appointment-service
    restart: unless-stopped
    environment:
      NODE_ENV: development
      PORT: 3006
      DATABASE_URL: postgresql://postgres:Supa201294base@db.kytphnasmdvebmdvvwtx.supabase.co:5432/postgres
      REDIS_URL: redis://:redis123@redis:6379
      JWT_SECRET: your-super-secret-jwt-key-change-in-production
      SUPABASE_URL: https://kytphnasmdvebmdvvwtx.supabase.co
      SUPABASE_ANON_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt5dHBobmFzbWR2ZWJtZHZ2d3R4Iiwicm9sIjoiYW5vbiIsImlhdCI6MTc1NTYyMjgxMCwiZXhwIjoyMDcxMTk4ODEwfQ.gfH3VNqxLZWAbjlrlk44VrBdyF1QKv7CyOSLmhFwbqA
      SUPABASE_SERVICE_ROLE_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt5dHBobmFzbWR2ZWJtZHZ2d3R4Iiwicm9sIjoic2VydmljZV9yb2xlIiwiaWF0IjoxNzU1NjIyODEwLCJleHAiOjIwNzExOTg4MTB9LjM2SXA5Tld2cWg2YWVGUXVvd1Y3OXI1NEMyWVFQYzVOLU1uX2RuMlFENzA
      # Configurações de conectividade
      DATABASE_CONNECTION_TIMEOUT: 30000
      DATABASE_POOL_SIZE: 10
      DATABASE_IDLE_TIMEOUT: 30000
    ports:
      - "3006:3006"
    volumes:
      - ./backend/services/appointment-service:/app:delegated
      - /app/node_modules
      - /app/.git
    networks:
      - atendeai-network
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3006/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    extra_hosts:
      - "host.docker.internal:host-gateway"
    dns:
      - 8.8.8.8
      - 8.8.4.4

  # =====================================================
  # PROMETHEUS (MONITORAMENTO)
  # =====================================================
  prometheus:
    image: prom/prometheus:latest
    container_name: atendeai-prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
    networks:
      - atendeai-network

  # =====================================================
  # GRAFANA (DASHBOARDS)
  # =====================================================
  grafana:
    image: grafana/grafana:latest
    container_name: atendeai-grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin123
      GF_USERS_ALLOW_SIGN_UP: false
    volumes:
      - grafana_data:/var/lib/grafana
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning:ro
    networks:
      - atendeai-network
    depends_on:
      - prometheus

# =====================================================
# VOLUMES
# =====================================================
volumes:
  redis_data:
    driver: local
  prometheus_data:
    driver: local
  grafana_data:
    driver: local

# =====================================================
# NETWORKS (OTIMIZADO)
# =====================================================
networks:
  atendeai-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
    # CORREÇÃO: Configurações de rede otimizadas
    driver_opts:
      com.docker.network.bridge.name: atendeai-br0
    # Configurações de DNS e conectividade
    enable_ipv6: false
