[build]
builder = "nixpacks"

[deploy]
startCommand = "node webhook-production.js"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[environment]
NODE_ENV = "production"
