# =====================================================
# CONFIGURAÇÃO KONG API GATEWAY - ENTREGÁVEL 1
# ATENDEAI 2.0
# =====================================================

_format_version: "2.1"
_transform: true

services:
  # =====================================================
  # AUTH SERVICE
  # =====================================================
  - name: auth-service
    url: http://auth-service:3001
    routes:
      - name: auth-login
        paths:
          - /api/v1/auth/login
        methods:
          - POST
        strip_path: false
        plugins:
          - name: rate-limiting
            config:
              minute: 5
              hour: 100
              policy: local
          - name: cors
            config:
              origins: ["*"]
              methods: ["POST", "OPTIONS"]
              headers: ["Content-Type", "Authorization"]
              exposed_headers: ["Authorization"]
              credentials: true
              max_age: 3600
          - name: request-transformer
            config:
              add:
                headers:
                  - "X-Service: auth"
                  - "X-Version: 1.0"

      - name: auth-refresh
        paths:
          - /api/v1/auth/refresh
        methods:
          - POST
        strip_path: false
        plugins:
          - name: rate-limiting
            config:
              minute: 10
              hour: 200
              policy: local
          - name: cors
            config:
              origins: ["*"]
              methods: ["POST", "OPTIONS"]
              headers: ["Content-Type", "Authorization"]
              exposed_headers: ["Authorization"]
              credentials: true
              max_age: 3600

      - name: auth-logout
        paths:
          - /api/v1/auth/logout
        methods:
          - POST
        strip_path: false
        plugins:
          - name: rate-limiting
            config:
              minute: 10
              hour: 200
              policy: local
          - name: cors
            config:
              origins: ["*"]
              methods: ["POST", "OPTIONS"]
              headers: ["Content-Type", "Authorization"]
              exposed_headers: ["Authorization"]
              credentials: true
              max_age: 3600

      - name: auth-validate
        paths:
          - /api/v1/auth/validate
        methods:
          - GET
        strip_path: false
        plugins:
          - name: rate-limiting
            config:
              minute: 100
              hour: 1000
              policy: local
          - name: cors
            config:
              origins: ["*"]
              methods: ["GET", "OPTIONS"]
              headers: ["Content-Type", "Authorization"]
              exposed_headers: ["Authorization"]
              credentials: true
              max_age: 3600

  # =====================================================
  # USER MANAGEMENT SERVICE
  # =====================================================
  - name: user-service
    url: http://user-service:3002
    routes:
      - name: users-crud
        paths:
          - /api/v1/users
        methods:
          - GET
          - POST
          - PUT
          - DELETE
        strip_path: false
        plugins:
          - name: rate-limiting
            config:
              minute: 30
              hour: 300
              policy: local
          - name: cors
            config:
              origins: ["*"]
              methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
              headers: ["Content-Type", "Authorization", "X-Clinic-ID"]
              exposed_headers: ["Authorization", "X-Clinic-ID"]
              credentials: true
              max_age: 3600
          - name: request-transformer
            config:
              add:
                headers:
                  - "X-Service: user"
                  - "X-Version: 1.0"

  # =====================================================
  # CLINIC SERVICE
  # =====================================================
  - name: clinic-service
    url: http://clinic-service:3003
    routes:
      - name: clinics-crud
        paths:
          - /api/v1/clinics
        methods:
          - GET
          - POST
          - PUT
          - DELETE
        strip_path: false
        plugins:
          - name: rate-limiting
            config:
              minute: 20
              hour: 200
              policy: local
          - name: cors
            config:
              origins: ["*"]
              methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
              headers: ["Content-Type", "Authorization", "X-Clinic-ID"]
              exposed_headers: ["Authorization", "X-Clinic-ID"]
              credentials: true
              max_age: 3600

  # =====================================================
  # HEALTH CHECK SERVICE
  # =====================================================
  - name: health-service
    url: http://health-service:3004
    routes:
      - name: health-check
        paths:
          - /health
          - /api/v1/health
        methods:
          - GET
        strip_path: false
        plugins:
          - name: cors
            config:
              origins: ["*"]
              methods: ["GET", "OPTIONS"]
              headers: ["Content-Type"]
              exposed_headers: []
              credentials: false
              max_age: 3600

# =====================================================
# PLUGINS GLOBAIS
# =====================================================
plugins:
  # =====================================================
  # LOGGING
  # =====================================================
  - name: file-log
    config:
      path: /var/log/kong/access.log
      reopen: true
      custom_fields_by_lua:
        - client_ip: "return kong.client.get_ip()"
        - user_agent: "return kong.request.get_header('User-Agent')"
        - clinic_id: "return kong.request.get_header('X-Clinic-ID')"

  # =====================================================
  # SECURITY HEADERS
  # =====================================================
  - name: response-transformer
    config:
      add:
        headers:
          - "X-Frame-Options: DENY"
          - "X-Content-Type-Options: nosniff"
          - "X-XSS-Protection: 1; mode=block"
          - "Referrer-Policy: strict-origin-when-cross-origin"
          - "Content-Security-Policy: default-src 'self'"

  # =====================================================
  # COMPRESSION
  # =====================================================
  - name: compression
    config:
      threshold: 1024
      level: 6

# =====================================================
# UPSTREAM HEALTH CHECKS
# =====================================================
upstreams:
  - name: auth-upstream
    healthchecks:
      active:
        type: http
        http_path: /health
        timeout: 1
        concurrency: 10
        interval: 10
        healthy:
          interval: 30
          successes: 2
        unhealthy:
          interval: 30
          http_failures: 3
          tcp_failures: 3
          timeouts: 3

  - name: user-upstream
    healthchecks:
      active:
        type: http
        http_path: /health
        timeout: 1
        concurrency: 10
        interval: 10
        healthy:
          interval: 30
          successes: 2
        unhealthy:
          interval: 30
          http_failures: 3
          tcp_failures: 3
          timeouts: 3

  - name: clinic-upstream
    healthchecks:
      active:
        type: http
        http_path: /health
        timeout: 1
        concurrency: 10
        interval: 10
        healthy:
          interval: 30
          successes: 2
        unhealthy:
          interval: 30
          http_failures: 3
          tcp_failures: 3
          timeouts: 3

# =====================================================
# CONFIGURAÇÕES DE SEGURANÇA
# =====================================================
# Kong Admin API
admin_listen: 0.0.0.0:8001
admin_gui_listen: 0.0.0.0:8002

# Kong Proxy
proxy_listen: 0.0.0.0:8000
proxy_listen_ssl: 0.0.0.0:8443

# Configurações de segurança
admin_gui_auth: basic-auth
admin_gui_session_conf:
  secret: your-super-secret-session-key-change-in-production
  storage: memory
  cookie_secure: false
  cookie_http_only: true
  cookie_same_site: Lax

# Rate limiting global
rate_limiting:
  policy: local
  redis:
    host: redis
    port: 6379
    database: 0
    timeout: 2000
    password: ""

# Logging
log_level: info
log_format: json
