{
  "openapi": "3.0.0",
  "info": {
    "title": "AtendeAí 2.0 API",
    "version": "2.0.0",
    "description": "API para sistema de gestão de clínicas com agenda própria"
  },
  "servers": [
    {
      "url": "http://localhost:3000",
      "description": "Development server"
    }
  ],
  "paths": {
    "/api/appointments": {
      "get": {
        "summary": "Listar agendamentos",
        "parameters": [
          {
            "name": "clinic_id",
            "in": "query",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "start_date",
            "in": "query",
            "schema": {
              "type": "string",
              "format": "date"
            }
          },
          {
            "name": "end_date",
            "in": "query",
            "schema": {
              "type": "string",
              "format": "date"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Lista de agendamentos",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/Appointment"
                  }
                }
              }
            }
          }
        }
      },
      "post": {
        "summary": "Criar agendamento",
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/CreateAppointmentRequest"
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Agendamento criado",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Appointment"
                }
              }
            }
          }
        }
      }
    },
    "/api/appointments/{id}": {
      "put": {
        "summary": "Atualizar agendamento",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/UpdateAppointmentRequest"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Agendamento atualizado",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Appointment"
                }
              }
            }
          }
        }
      },
      "delete": {
        "summary": "Excluir agendamento",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "204": {
            "description": "Agendamento excluído"
          }
        }
      }
    },
    "/api/appointments/availability": {
      "get": {
        "summary": "Obter horários disponíveis",
        "parameters": [
          {
            "name": "clinic_id",
            "in": "query",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "date",
            "in": "query",
            "required": true,
            "schema": {
              "type": "string",
              "format": "date"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Horários disponíveis",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "type": "object",
                    "properties": {
                      "start_time": {
                        "type": "string",
                        "format": "time"
                      },
                      "end_time": {
                        "type": "string",
                        "format": "time"
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "Appointment": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string",
            "format": "uuid"
          },
          "clinic_id": {
            "type": "string",
            "format": "uuid"
          },
          "user_id": {
            "type": "string",
            "format": "uuid"
          },
          "patient_name": {
            "type": "string"
          },
          "patient_phone": {
            "type": "string"
          },
          "patient_email": {
            "type": "string"
          },
          "appointment_date": {
            "type": "string",
            "format": "date-time"
          },
          "duration_minutes": {
            "type": "integer"
          },
          "status": {
            "type": "string",
            "enum": [
              "scheduled",
              "confirmed",
              "cancelled",
              "completed"
            ]
          },
          "notes": {
            "type": "string"
          },
          "created_at": {
            "type": "string",
            "format": "date-time"
          },
          "updated_at": {
            "type": "string",
            "format": "date-time"
          }
        }
      },
      "CreateAppointmentRequest": {
        "type": "object",
        "required": [
          "clinic_id",
          "patient_name",
          "appointment_date"
        ],
        "properties": {
          "clinic_id": {
            "type": "string",
            "format": "uuid"
          },
          "patient_name": {
            "type": "string"
          },
          "patient_phone": {
            "type": "string"
          },
          "patient_email": {
            "type": "string"
          },
          "appointment_date": {
            "type": "string",
            "format": "date-time"
          },
          "duration_minutes": {
            "type": "integer",
            "default": 30
          },
          "notes": {
            "type": "string"
          }
        }
      },
      "UpdateAppointmentRequest": {
        "type": "object",
        "properties": {
          "patient_name": {
            "type": "string"
          },
          "patient_phone": {
            "type": "string"
          },
          "patient_email": {
            "type": "string"
          },
          "appointment_date": {
            "type": "string",
            "format": "date-time"
          },
          "duration_minutes": {
            "type": "integer"
          },
          "status": {
            "type": "string",
            "enum": [
              "scheduled",
              "confirmed",
              "cancelled",
              "completed"
            ]
          },
          "notes": {
            "type": "string"
          }
        }
      }
    }
  }
}