openapi: 3.0.3
info:
  title: AtendeAí 2.0 API
  description: API para funcionalidades pendentes
  version: 1.0.0
  contact:
    name: AtendeAí Team
    email: dev@atendeai.com

servers:
  - url: http://localhost:3000/api
    description: Development server
  - url: https://atendeai.railway.app/api
    description: Production server

paths:
  /conversations/{id}/messages:
    post:
      summary: Enviar mensagem
      tags: [Conversations]
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                message:
                  type: string
                sender:
                  type: string
              required: [message, sender]
      responses:
        '200':
          description: Mensagem enviada com sucesso
        '400':
          description: Erro na requisição
        '404':
          description: Conversa não encontrada

  /conversations/{id}/assign:
    put:
      summary: Atribuir conversa
      tags: [Conversations]
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                assigned_user_id:
                  type: string
                mode:
                  type: string
                  enum: [manual, auto]
              required: [assigned_user_id, mode]
      responses:
        '200':
          description: Conversa atribuída com sucesso
        '400':
          description: Erro na requisição
        '404':
          description: Conversa não encontrada

  /clinics:
    post:
      summary: Criar clínica
      tags: [Clinics]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                whatsapp_number:
                  type: string
                context_json:
                  type: object
              required: [name, whatsapp_number]
      responses:
        '201':
          description: Clínica criada com sucesso
        '400':
          description: Erro na requisição

  /clinics/{id}:
    put:
      summary: Editar clínica
      tags: [Clinics]
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                whatsapp_number:
                  type: string
                context_json:
                  type: object
      responses:
        '200':
          description: Clínica editada com sucesso
        '400':
          description: Erro na requisição
        '404':
          description: Clínica não encontrada

  /auth/login:
    post:
      summary: Login de usuário
      tags: [Auth]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                login:
                  type: string
                password:
                  type: string
              required: [login, password]
      responses:
        '200':
          description: Login realizado com sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                  user:
                    type: object
        '401':
          description: Credenciais inválidas
