openapi: 3.1.0
info:
  title: AtendeAI 2.0 API
  version: 1.3.0
  description: API para sistema de gestão de clínicas

servers:
  - url: http://localhost:8000
    description: Development server

paths:
  /auth/supabase:
    post:
      summary: Autenticação via Supabase
      tags: [Authentication]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
                  minLength: 6

